name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]   # cambia si usas otra rama
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATRIMONIO_AEF95 }}'
          channelId: live
          projectId: 'matrimonio-aef95'